apiVersion: v1
kind: Service
metadata:

  labels:

    service: udaconnect-consumer-api

  name: udaconnect-consumer-api
  author: okaxel
  repository: https://github.com/okaxel/UdaConnect/

spec:

  ports:

  - name: "9093"
    port: 9093
    targetPort: 9093
    nodePort: 30004

  selector:

    service: udaconnect-consumer-api

  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:

  labels:

    service: udaconnect-consumer-api

  name: udaconnect-consumer-api
  author: okaxel
  repository: https://github.com/okaxel/UdaConnect/

spec:

  replicas: 1
  selector:

    matchLabels:

      service: udaconnect-consumer-api

  template:

    metadata:

      labels:

        service: udaconnect-consumer-api

    spec:

      containers:

      - image: okaxel/udaconnect-consumer-api:latest
        name: udaconnect-consumer-api
        imagePullPolicy: Always
        env:

        - name: DB_USERNAME
          valueFrom:

            configMapKeyRef:

              name: db-env
              key: DB_USERNAME

        - name: DB_PASSWORD
          valueFrom:

            secretKeyRef:

              name: db-secret
              key: DB_PASSWORD

        - name: DB_NAME
          valueFrom:

            configMapKeyRef:

              name: db-env
              key: DB_NAME

        - name: DB_HOST
          valueFrom:

            configMapKeyRef:

              name: db-env
              key: DB_HOST

        - name: DB_PORT
          valueFrom:

            configMapKeyRef:

              name: db-env
              key: DB_PORT

      restartPolicy: Always
