# According to https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
# Secrets naming convention: https://docs.docker.com/ci-cd/github-actions/
# Also consulted: https://github.com/marketplace/actions/build-and-push-docker-images
name: UdaConnect - Package with Docker

on:

  push:

    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:

          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push (app frontend)
        uses: docker/build-push-action@v2
        with:

          context: ./modules/frontend
          file: ./modules/frontend/Dockerfile
          push: true
          tags: okaxel/udaconnect-app:latest

      - name: Build and push (location)
        uses: docker/build-push-action@v2
        with:

          context: ./modules/location_api
          file: ./modules/location_api/Dockerfile
          push: true
          tags: okaxel/udaconnect-location-api:latest

      - name: Build and push (pac)
        uses: docker/build-push-action@v2
        with:

          context: ./modules/pac_api
          file: ./modules/pac_api/Dockerfile
          push: true
          tags: okaxel/udaconnect-pac-api:latest

      - name: Build and push (consumer)
        uses: docker/build-push-action@v2
        with:

          context: ./modules/consumer_api
          file: ./modules/consumer_api/Dockerfile
          push: true
          tags: okaxel/udaconnect-consumer-api:latest

      - name: Build and push (grpc)
        uses: docker/build-push-action@v2
        with:

          context: ./modules/grpc_api
          file: ./modules/grpc_api/Dockerfile
          push: true
          tags: okaxel/udaconnect-grpc-api:latest
